//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyCab.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DriverDetails")]
    public partial class DriverDetail
    {
        [Key]
        public string DriverId { get; set; }
        public string Name { get; set; }
        public long ContactNumber { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Status { get; set; }
    }
}
